(()=>{'use strict';
const A=v=>Array.isArray(v)?v:(v==null?[]:[v]);
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const stamp=r=>new Date(`${r?.date||'1970-01-01'}T${r?.time||'00:00'}:00+09:00`).getTime()||0;
const direction=v=>/上昇|強気|買い/.test(v||'')?1:/下落|弱気|売り/.test(v||'')?-1:0;
let reports=[],report=null,lastId='';
function selectedId(){return document.querySelector('#reportSelect')?.value||''}
function syncSelected(){const id=selectedId();report=(id&&reports.find(r=>String(r.id)===String(id)))||reports[0]||null;return report}
async function getReports(){const res=await fetch(`reports.json?v5=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw Error('reports.json');const j=await res.json();return (Array.isArray(j)?j:A(j.reports)).sort((a,b)=>stamp(b)-stamp(a))}
function marketStance(r){const scores=A(r.markets).map(m=>direction(m.direction));const total=scores.reduce((a,b)=>a+b,0);const riskOffSignals=A(r.markets).filter(m=>['日経225先物','BTCUSD','金'].some(k=>(m.name||'').includes(k))&&direction(m.direction)<0).length;let label='Neutral',cls='neutral',note='方向が分散。金利・為替・株式の次の連動を確認。';if(total>=2&&riskOffSignals===0){label='Risk On';cls='risk-on';note='リスク資産への資金流入が優勢。追随買いは金利とドルの確認が必要。'}else if(total<=-2||riskOffSignals>=2){label='Risk Off';cls='risk-off';note='防御姿勢が優勢。戻り局面でも需給悪化と金利上昇に注意。'}return{label,cls,note,total}}
function causalNodes(r){const names=A(r.markets).reduce((o,m)=>(o[m.name]=m,o),{});const usd=names['USD/JPY'],gold=names['金'],nikkei=names['日経225先物'],btc=names['BTCUSD'],oil=names['原油'];const rate=A(r.rates).find(x=>(x.name||'').includes('米10年'));const rateText=rate?`米10年 ${rate.value}`:'米金利';return[{k:'driver',t:rateText,s:'高止まりならドルを支え、グロース株と金の重石'},{k:'fx',t:`ドル円 ${usd?.price||'—'}`,s:usd?.shortOutlook||'金利差と実需・政策発言を確認'},{k:'assets',t:`金 ${gold?.direction||'—'} / BTC ${btc?.direction||'—'}`,s:'ドル流動性とリスク選好の影響を受ける'},{k:'equity',t:`日経先物 ${nikkei?.direction||'—'}`,s:nikkei?.shortOutlook||'先物需給と円安の副作用を確認'},{k:'commodity',t:`原油 ${oil?.direction||'—'}`,s:oil?.shortOutlook||'インフレ期待と供給要因を確認'}]}
function stars(m){let n=3;const d=direction(m.direction);if(d!==0)n++;const buys=A(m.buyReasons).length,sells=A(m.sellReasons).length;if(d>0&&buys>sells)n=5;if(d<0&&sells>buys)n=5;if(/中立|レンジ/.test(m.direction||''))n=2;return Math.max(1,Math.min(5,n))}
function addStrength(r){const cards=[...document.querySelectorAll('.market-card')];cards.forEach((card,i)=>{card.querySelector('.signal-strength')?.remove();const m=A(r.markets)[i];if(!m)return;const n=stars(m),box=document.createElement('div');box.className='signal-strength';box.innerHTML=`<span>シグナル強度</span><b aria-label="5段階中${n}">${'<i>★</i>'.repeat(n)}${'<i class="off">★</i>'.repeat(5-n)}</b><small>方向の確度ではなく、材料の偏り</small>`;const price=card.querySelector('.market-change');(price||card.querySelector('.market-head')).insertAdjacentElement('afterend',box)})}
function enhance(r){const dash=document.querySelector('#dashboard');if(!dash||!dash.querySelector('.control-bar'))return;const id=String(r.id||`${r.date}-${r.time}`);dash.querySelectorAll('.v5-statement,.causal-section').forEach(x=>x.remove());const stance=marketStance(r),control=dash.querySelector('.control-bar');control.insertAdjacentHTML('afterend',`<section class="v5-statement ${stance.cls}" data-report-id="${E(id)}"><div class="stance-label"><small>TODAY'S MARKET STANCE</small><strong>${stance.label}</strong></div><div class="stance-copy"><b>今日の結論</b><span>${E(stance.note)}</span></div><div class="stance-watch"><b>監視条件</b><span>${E(r.breakConditions||'主要市場の連動が変化する条件を確認')}</span></div></section>`);const nodes=causalNodes(r),marketHeading=dash.querySelector('#s6');if(marketHeading){marketHeading.insertAdjacentHTML('beforebegin',`<section class="causal-section" id="causal" data-report-id="${E(id)}"><div class="section-heading causal-heading"><div><span>MARKET TRANSMISSION</span><h2>今日の相場を動かす因果関係</h2></div><p>材料 → 金利・為替 → 資金フロー → 価格反応</p></div><div class="causal-chain">${nodes.map((n,i)=>`${i?'<div class="causal-arrow">→</div>':''}<article class="causal-node ${n.k}"><b>${E(n.t)}</b><span>${E(n.s)}</span></article>`).join('')}</div><p class="causal-note">矢印は固定的な因果を断定するものではなく、当日の主要な伝播経路を整理したものです。</p></section>`)}addStrength(r);lastId=id}
async function refresh(){try{reports=await getReports();syncSelected();if(report)enhance(report)}catch(e){console.error('V5 enhancement:',e)}}
document.addEventListener('change',e=>{if(e.target?.id==='reportSelect')setTimeout(()=>{syncSelected();if(report)enhance(report)},0)});
const obs=new MutationObserver(()=>{const before=lastId;syncSelected();const id=String(report?.id||'');if(report&&(!document.querySelector('.v5-statement')||id!==before))enhance(report)});obs.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('DOMContentLoaded',()=>{refresh();setInterval(refresh,300000)});
})();