const DS_ALIASES={"USD/JPY":["USD/JPY","USDJPY","ドル円"],"EUR/USD":["EUR/USD","EURUSD","ユーロドル"],"日経225先物":["日経225先物","日経先物","大阪取引所"],"金":["金","ゴールド","Gold","XAUUSD"],"原油":["原油","WTI","ブレント","Crude Oil"],"BTCUSD":["BTCUSD","BTC/USD","ビットコイン","Bitcoin"]};
const DS_HORIZONS=["nextDay","threeDays","oneWeek","oneMonth"];
function dsArray(value){return Array.isArray(value)?value:(value?[value]:[]);}
function dsText(value){return typeof value==="string"?value:(value?.text||value?.summary||value?.title||"");}
function dsMarketName(raw=""){const decoded=decodeURIComponent(raw).trim();const found=Object.entries(DS_ALIASES).find(([,aliases])=>aliases.some(alias=>alias.toLowerCase()===decoded.toLowerCase()));return found?.[0]||decoded||"USD/JPY";}
function dsMatches(market,name){const text=[market?.name,market?.symbol,market?.ticker].filter(Boolean).join(" ").toLowerCase();return (DS_ALIASES[name]||[name]).some(alias=>text.includes(alias.toLowerCase()));}
function dsDirection(value=""){const text=String(value).toLowerCase();if(/上昇|強気|買い|反発|上向|bull|up/.test(text))return "up";if(/下落|弱気|売り|反落|下向|bear|down/.test(text))return "down";return "neutral";}
function dsOutcomeClass(value){const result=typeof value==="string"?value:value?.result||"";if(/◎|的中|hit/i.test(result))return "hit";if(/○|一部|partial/i.test(result))return "partial";if(/×|不的中|外れ|miss/i.test(result))return "miss";return "pending";}
function dsReportText(row){const {report,market}=row;return [report?.title,report?.theme,report?.leadingMarket,...dsArray(report?.news).map(dsText),...dsArray(report?.changes).map(dsText),...dsArray(report?.crossAssetFlow).map(dsText),...dsArray(report?.positioning).map(dsText),...dsArray(report?.events).map(dsText),market?.direction,market?.material,market?.outlook,market?.positioning,market?.mainScenario,market?.alternativeScenario,market?.breakCondition,market?.risk].filter(Boolean).join(" ").toLowerCase();}
function dsTokens(row){return new Set(dsReportText(row).replace(/[、。・,./()（）「」『』:：;；!?！？]/g," ").split(/\s+/).flatMap(part=>part.match(/[a-z0-9/_-]+|[一-龠ぁ-んァ-ヶー]{2,}/gi)||[]).filter(word=>word.length>1&&!/^(相場|市場|今回|今後|レポート|こと|もの|ため|する|した|して|いる|ある)$/.test(word)));}
function dsJaccard(a,b){const union=new Set([...a,...b]);if(!union.size)return 0;let overlap=0;a.forEach(value=>{if(b.has(value))overlap++;});return overlap/union.size;}
function dsSimilarity(a,b){const token=dsJaccard(dsTokens(a),dsTokens(b));const direction=dsDirection(a.market?.direction)===dsDirection(b.market?.direction)?1:0;const leaderA=String(a.report?.leadingMarket||"").toLowerCase(),leaderB=String(b.report?.leadingMarket||"").toLowerCase();const leader=leaderA&&leaderB&&(leaderA.includes(leaderB)||leaderB.includes(leaderA))?1:0;return Math.round((token*.75+direction*.2+leader*.05)*100);}
function dsHistoricalSignal(row){const direction=dsDirection(row.market?.direction);const outcomes=DS_HORIZONS.map(key=>row.market?.outcomes?.[key]).filter(Boolean).map(dsOutcomeClass).filter(value=>value!=="pending");if(!outcomes.length||direction==="neutral")return null;let score=0;outcomes.forEach(result=>{if(result==="hit")score+=direction==="up"?1:-1;else if(result==="miss")score+=direction==="up"?-1:1;});return score>0?"up":score<0?"down":"neutral";}
function dsUnique(values){return [...new Set(values.map(dsText).map(value=>String(value).trim()).filter(Boolean))];}
function dsScenarioData(current){const report=current?.report||{},market=current?.market||{};return {
  main:market.mainScenario||market.outlook||report.theme||"最新レポートにメインシナリオの記載がありません。",
  bullish:dsUnique([market.bullishCondition,market.bullCase,...dsArray(report.bullishFactors),...dsArray(report.positiveFactors)]),
  bearish:dsUnique([market.bearishCondition,market.bearCase,...dsArray(report.bearishFactors),...dsArray(report.negativeFactors)]),
  invalidation:market.breakCondition||market.invalidation||market.risk||"崩れる条件の記載がありません。",
  events:dsUnique([...dsArray(report.events),...dsArray(report.watchEvents),...dsArray(report.news)]).slice(0,5)
};}
function dsList(items,empty){return items.length?`<ul>${items.map(item=>`<li>${item}</li>`).join("")}</ul>`:`<p class="ds-empty">${empty}</p>`;}
function buildDecisionSupport(rows){if(document.querySelector(".decision-support-panel"))return;const current=rows[0];const panel=document.createElement("section");panel.className="decision-support-panel";if(!current){panel.innerHTML=`<div class="ds-head"><div><span>DECISION SUPPORT</span><h2>売買判断支援</h2></div></div><p class="ds-empty">分析対象のレポートがありません。</p>`;document.querySelector(".natural-search-section")?.before(panel);return;}
  const comparable=rows.slice(1).map(row=>({row,similarity:dsSimilarity(current,row),signal:dsHistoricalSignal(row)})).filter(item=>item.signal&&item.similarity>0).sort((a,b)=>b.similarity-a.similarity).slice(0,10);
  const weights={up:0,neutral:0,down:0};let totalWeight=0;comparable.forEach(item=>{const weight=Math.max(item.similarity,10);weights[item.signal]+=weight;totalWeight+=weight;});
  const probabilities=totalWeight?Object.fromEntries(Object.entries(weights).map(([key,value])=>[key,Math.round(value/totalWeight*100)])):{up:null,neutral:null,down:null};
  const confidence=comparable.length>=5?"高":comparable.length>=2?"中":"低";const scenario=dsScenarioData(current);const currentDirection=dsDirection(current.market?.direction);const directionLabel=currentDirection==="up"?"強気":currentDirection==="down"?"弱気":"中立";
  panel.innerHTML=`<div class="ds-head"><div><span>DECISION SUPPORT</span><h2>売買判断支援</h2></div><div class="ds-confidence">信頼度 <strong>${confidence}</strong><small>類似・検証済み ${comparable.length}件</small></div></div><div class="ds-summary"><div><span>現在の方向感</span><strong class="${currentDirection}">${directionLabel}</strong></div><div><span>メインシナリオ</span><p>${scenario.main}</p></div></div><div class="ds-probabilities"><article class="up"><span>強気確率</span><strong>${probabilities.up===null?"—":`${probabilities.up}%`}</strong></article><article class="neutral"><span>中立確率</span><strong>${probabilities.neutral===null?"—":`${probabilities.neutral}%`}</strong></article><article class="down"><span>弱気確率</span><strong>${probabilities.down===null?"—":`${probabilities.down}%`}</strong></article></div><div class="ds-grid"><article><h3>強気条件</h3>${dsList(scenario.bullish,"明示された強気条件はありません。")}</article><article><h3>弱気条件</h3>${dsList(scenario.bearish,"明示された弱気条件はありません。")}</article><article><h3>シナリオが崩れる条件</h3><p>${scenario.invalidation}</p></article><article><h3>監視イベント</h3>${dsList(scenario.events,"監視イベントの記載はありません。")}</article></div><div class="ds-analogs"><h3>判断に使った類似局面</h3>${comparable.length?comparable.slice(0,5).map(({row,similarity,signal})=>`<div><span>${row.report?.date?.replaceAll("-","/")||"—"} ${row.report?.time||""}</span><b>類似度 ${similarity}%</b><strong class="${signal}">${signal==="up"?"その後は強気":signal==="down"?"その後は弱気":"その後は中立"}</strong></div>`).join(""):`<p class="ds-empty">確認済み outcomes を持つ類似レポートが不足しています。確率は表示しません。</p>`}</div><p class="ds-note">確率は保存済みレポートと確認済み outcomes の機械的集計です。価格を予測して補完せず、データが不足する場合は「—」と表示します。</p>`;document.querySelector(".natural-search-section")?.before(panel);}
async function initDecisionSupport(){try{const params=new URLSearchParams(location.search),name=dsMarketName(params.get("market")||params.get("name")||"");const response=await fetch(`reports.json?decision=${Date.now()}`,{cache:"no-store"});if(!response.ok)return;const reports=await response.json();if(!Array.isArray(reports))return;const rows=reports.flatMap(report=>dsArray(report.markets).filter(market=>dsMatches(market,name)).map(market=>({report,market}))).sort((a,b)=>`${b.report?.date||""} ${b.report?.time||""}`.localeCompare(`${a.report?.date||""} ${a.report?.time||""}`));buildDecisionSupport(rows);}catch(error){console.warn("Decision support could not be built",error);}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initDecisionSupport);else initDecisionSupport();
