const MI_ALIASES={"USD/JPY":["USD/JPY","USDJPY","ドル円"],"EUR/USD":["EUR/USD","EURUSD","ユーロドル"],"日経225先物":["日経225先物","日経先物","大阪取引所"],"金":["金","ゴールド","Gold","XAUUSD"],"原油":["原油","WTI","ブレント","Crude Oil"],"BTCUSD":["BTCUSD","BTC/USD","ビットコイン","Bitcoin"]};
const MI_THEMES={"米金利":["米金利","米10年","利回り","FRB","FOMC"],"日銀・円金利":["日銀","円金利","国債","利上げ","植田"],"実需・仲値":["実需","仲値","輸入","輸出","ゴトー日"],"原油・エネルギー":["原油","WTI","OPEC","エネルギー","ガソリン"],"地政学":["中東","制裁","戦争","地政学","ホルムズ"],"AI・半導体":["AI","半導体","NVIDIA","エヌビディア","SOX"],"SQ・オプション":["SQ","MSQ","オプション","ガンマ","建玉"],"CTA・需給":["CTA","需給","ポジション","先物","ETF","フロー"],"リスク選好":["リスクオン","リスクオフ","Fear","VIX","安全資産"],"暗号資産":["暗号資産","ビットコイン","BTC","ETF","ステーブルコイン"]};
const miArr=v=>Array.isArray(v)?v:(v?[v]:[]);const miEsc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function miName(raw=""){const d=decodeURIComponent(raw).trim();return Object.entries(MI_ALIASES).find(([,a])=>a.some(x=>x.toLowerCase()===d.toLowerCase()))?.[0]||d||"USD/JPY";}
function miMatch(m,n){const t=[m?.name,m?.symbol,m?.ticker].filter(Boolean).join(" ").toLowerCase();return (MI_ALIASES[n]||[n]).some(a=>t.includes(a.toLowerCase()));}
function miText(r,m){return [r?.title,r?.theme,r?.leadingMarket,...miArr(r?.news),...miArr(r?.changes),...miArr(r?.positioning),...miArr(r?.crossAssetFlow),...miArr(r?.events),...miArr(r?.handover),m?.direction,m?.outlook,m?.material,m?.positioning,m?.mainScenario,m?.alternativeScenario,m?.breakCondition,m?.risk].filter(Boolean).join(" ");}
function miDir(x=""){if(/上昇|強気|買い|反発|底堅|円安/.test(x))return"up";if(/下落|弱気|売り|反落|軟調|円高/.test(x))return"down";return"neutral";}
function miOutcome(m){const vals=Object.values(m?.outcomes||{}).map(x=>typeof x==="string"?x:x?.result).filter(Boolean);if(vals.includes("◎"))return 1;if(vals.includes("○"))return .5;if(vals.includes("×"))return 0;return null;}
function miThemes(text){return Object.entries(MI_THEMES).filter(([,keys])=>keys.some(k=>text.includes(k))).map(([name])=>name);}
function miDate(r){return `${r?.date||""} ${r?.time||""}`.trim();}
function miPanel(cls,label,title){const s=document.createElement("section");s.className=`${cls} insight-card mi-panel`;s.innerHTML=`<div class="mi-head"><div><span>${label}</span><h2>${title}</h2></div></div><div class="mi-body"></div>`;return s;}
function buildAssistant(rows,name){const p=miPanel("report-assistant-panel","REPORT ASSISTANT","次回レポート作成アシスタント"),b=p.querySelector(".mi-body"),latest=rows[0];if(!latest){b.innerHTML='<p class="mi-empty">レポートデータがありません。</p>';return p;}const text=miText(latest.report,latest.market),themes=miThemes(text),dir=latest.market?.direction||"方向感未記載",missing=[];if(!latest.market?.material&&!miArr(latest.report?.news).length)missing.push("主要材料");if(!latest.market?.positioning&&!miArr(latest.report?.positioning).length)missing.push("需給・ポジション");if(!latest.market?.alternativeScenario)missing.push("代替シナリオ");if(!latest.market?.breakCondition)missing.push("崩れる条件");if(!miArr(latest.report?.events).length)missing.push("今後のイベント");const draft=[`【現在の方向感】${dir}`,`【主要テーマ】${themes.join("、")||"テーマ未抽出"}`,`【メインシナリオ】${latest.market?.mainScenario||latest.market?.outlook||"要入力"}`,`【需給・ポジション】${latest.market?.positioning||miArr(latest.report?.positioning)[0]||"要入力"}`,`【代替シナリオ】${latest.market?.alternativeScenario||"要入力"}`,`【崩れる条件】${latest.market?.breakCondition||latest.market?.risk||"要入力"}`,`【次のイベント】${miArr(latest.report?.events).join("、")||"要入力"}`];b.innerHTML=`<div class="mi-summary"><strong>${miEsc(name)}の次回レポート骨子</strong><span>${miEsc(miDate(latest.report))}を基準</span></div><pre class="mi-draft">${miEsc(draft.join("\n\n"))}</pre><div class="mi-actions"><button type="button" class="mi-copy">骨子をコピー</button><span>${missing.length?`不足：${miEsc(missing.join("、"))}`:"主要項目はそろっています"}</span></div>`;b.querySelector(".mi-copy")?.addEventListener("click",async e=>{try{await navigator.clipboard.writeText(draft.join("\n\n"));e.currentTarget.textContent="コピーしました";}catch{e.currentTarget.textContent="コピーできませんでした";}});return p;}
function buildTransition(rows){const p=miPanel("theme-transition-panel","THEME TRANSITION","相場テーマ遷移マップ"),b=p.querySelector(".mi-body");const items=rows.slice(0,12).reverse().map(x=>({date:miDate(x.report),themes:miThemes(miText(x.report,x.market))})).filter(x=>x.themes.length);if(!items.length){b.innerHTML='<p class="mi-empty">テーマ遷移を描くための実データが不足しています。</p>';return p;}b.innerHTML=`<div class="mi-timeline">${items.map((x,i)=>`<article><time>${miEsc(x.date)}</time><div>${x.themes.map(t=>`<span>${miEsc(t)}</span>`).join("")}</div>${i<items.length-1?'<b>→</b>':''}</article>`).join("")}</div>`;return p;}
function buildAccuracy(rows){const p=miPanel("accuracy-improvement-panel","ACCURACY IMPROVEMENT","予測精度の改善提案"),b=p.querySelector(".mi-body"),scored=rows.map(x=>({x,score:miOutcome(x.market),themes:miThemes(miText(x.report,x.market)),hour:(x.report?.time||"").slice(0,2)})).filter(x=>x.score!==null);if(scored.length<3){b.innerHTML='<p class="mi-empty">確定済み outcomes が3件以上たまると、改善提案を表示します。現時点では推測による評価を行いません。</p>';return p;}const groupBy=key=>{const map={};scored.forEach(r=>miArr(key(r)).forEach(k=>{if(!k)return;(map[k]??=[]).push(r.score);}));return Object.entries(map).map(([k,v])=>({k,n:v.length,avg:v.reduce((a,c)=>a+c,0)/v.length})).filter(x=>x.n>=2).sort((a,b)=>b.avg-a.avg);};const themes=groupBy(r=>r.themes),hours=groupBy(r=>r.hour),best=themes[0],worst=[...themes].sort((a,b)=>a.avg-b.avg)[0],bestHour=hours[0];const suggestions=[];if(best)suggestions.push(`${best.k}では加重精度${Math.round(best.avg*100)}%。このテーマの判断手順を標準化する。`);if(worst&&worst!==best)suggestions.push(`${worst.k}では加重精度${Math.round(worst.avg*100)}%。代替シナリオと無効化条件を強化する。`);if(bestHour)suggestions.push(`${bestHour}時台の精度が相対的に高い。情報取得時点と予測期間を揃えて再検証する。`);b.innerHTML=`<div class="mi-metrics"><article><span>検証件数</span><strong>${scored.length}</strong></article><article><span>全体加重精度</span><strong>${Math.round(scored.reduce((a,c)=>a+c.score,0)/scored.length*100)}%</strong></article><article><span>高精度テーマ</span><strong>${miEsc(best?.k||"—")}</strong></article></div><ol class="mi-suggestions">${suggestions.map(s=>`<li>${miEsc(s)}</li>`).join("")}</ol>`;return p;}
function buildChecklist(rows,name){const p=miPanel("trade-checklist-panel","TRADE CHECKLIST","売買前チェックリスト"),b=p.querySelector(".mi-body"),latest=rows[0];if(!latest){b.innerHTML='<p class="mi-empty">チェック対象がありません。</p>';return p;}const text=miText(latest.report,latest.market);const items=[
["価格と方向感を確認",Boolean(latest.market?.price&&latest.market?.direction)],
["材料→金利・為替→価格反応を確認",/金利|利回り|ドル|円|為替|FRB|日銀/i.test(text)],
["何が買われ、何が売られたかを確認",/買われ|売られ|流入|流出|資金フロー/i.test(text)||miArr(latest.report?.crossAssetFlow).length>0],
["実需・仲値・輸出入フローを確認",/実需|仲値|輸入|輸出|ゴトー日/i.test(text)],
["CTA・先物・オプション・SQ需給を確認",/CTA|先物|オプション|SQ|MSQ|ガンマ|建玉/i.test(text)],
["主要ニュースと次のイベントを確認",miArr(latest.report?.news).length>0&&miArr(latest.report?.events).length>0],
["メインシナリオを確認",Boolean(latest.market?.mainScenario||latest.market?.outlook)],
["代替シナリオを確認",Boolean(latest.market?.alternativeScenario)],
["損切り・無効化条件を確認",Boolean(latest.market?.breakCondition||latest.market?.risk)],
["ポジションサイズを決定",false]
];b.innerHTML=`<div class="mi-check-progress"><strong>0/${items.length}</strong><span>手動確認を含むため、初期状態では未完了です</span></div><div class="mi-checklist">${items.map(([label,auto],i)=>`<label><input type="checkbox" ${auto?"checked":""} data-index="${i}"><span>${miEsc(label)}</span><small>${auto?"レポート内に関連記載あり":"要確認"}</small></label>`).join("")}</div><p class="mi-note">記載ありは安全や売買適否を保証しません。実際の価格、ニュース、注文条件を発注前に再確認してください。</p>`;const boxes=[...b.querySelectorAll('input[type="checkbox"]')],progress=b.querySelector(".mi-check-progress strong"),update=()=>progress.textContent=`${boxes.filter(x=>x.checked).length}/${boxes.length}`;boxes.forEach(x=>x.addEventListener("change",update));update();return p;}
async function initMISuite(){try{const q=new URLSearchParams(location.search),name=miName(q.get("market")||"");const res=await fetch(`reports.json?mi=${Date.now()}`,{cache:"no-store"});if(!res.ok)return;const reports=await res.json();const rows=(Array.isArray(reports)?reports:[]).flatMap(report=>miArr(report.markets).filter(m=>miMatch(m,name)).map(market=>({report,market}))).sort((a,b)=>miDate(b.report).localeCompare(miDate(a.report)));const anchor=document.querySelector(".natural-search-section");if(!anchor)return;const frag=document.createDocumentFragment();frag.append(buildAssistant(rows,name),buildTransition(rows),buildAccuracy(rows),buildChecklist(rows,name));anchor.before(frag);}catch(e){console.warn("Intelligence suite unavailable",e);}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initMISuite);else initMISuite();
