const $=id=>document.getElementById(id);
const marketPageTitle=$("marketPageTitle"),marketPageLead=$("marketPageLead"),marketReportCount=$("marketReportCount"),marketLatestDirection=$("marketLatestDirection"),marketTopTheme=$("marketTopTheme"),marketLatestDate=$("marketLatestDate"),directionHistory=$("directionHistory"),marketThemeRanking=$("marketThemeRanking"),marketArchive=$("marketArchive"),marketArchiveCount=$("marketArchiveCount"),marketEmpty=$("marketEmpty"),scenarioReview=$("scenarioReview"),scenarioReviewStatus=$("scenarioReviewStatus"),marketSimilarReports=$("marketSimilarReports"),themeTimeline=$("themeTimeline"),marketFlowMap=$("marketFlowMap"),marketNetwork=$("marketNetwork"),bullishRate=$("bullishRate"),bearishRate=$("bearishRate"),directionChanges=$("directionChanges"),dominantTime=$("dominantTime"),marketSearchForm=$("marketSearchForm"),marketSearchInput=$("marketSearchInput"),marketSearchStatus=$("marketSearchStatus"),marketSearchResults=$("marketSearchResults");
let currentRows=[],currentMarket="USD/JPY";

const MARKET_ALIASES={"USD/JPY":["USD/JPY","USDJPY","ドル円"],"EUR/USD":["EUR/USD","EURUSD","ユーロドル"],"日経225先物":["日経225先物","日経先物","大阪取引所"],"金":["金","ゴールド","Gold","XAUUSD"],"原油":["原油","WTI","ブレント","Crude Oil"],"BTCUSD":["BTCUSD","BTC/USD","ビットコイン","Bitcoin"]};
const THEMES=[["米金利",["米金利","米長期金利","米10年債","国債利回り"]],["金融政策",["FRB","FOMC","日銀","ECB","利上げ","利下げ"]],["インフレ",["インフレ","CPI","PCE","物価","期待インフレ"]],["地政学",["地政学","中東","ホルムズ","制裁","戦争","紛争"]],["実需・需給",["実需","需給","ポジション","フロー","買い戻し","ショートカバー"]],["オプション・先物",["オプション","SQ","MSQ","ガンマ","先物建玉"]],["AI・半導体",["AI","半導体","NASDAQ","NVIDIA","エヌビディア"]],["原油・エネルギー",["原油","WTI","ブレント","OPEC","エネルギー"]],["暗号資産",["BTC","ビットコイン","暗号資産","ETF資金"]],["リスク選好",["リスクオン","リスクオフ","安全資産","安全逃避"]]];
const STOP_WORDS=new Set(["した","して","いる","ある","その","この","こと","もの","局面","相場","市場","レポート","とき","場合","前","後"]);

function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function asArray(v){return Array.isArray(v)?v:(v?[v]:[]);}function textOf(v){return typeof v==="string"?v:(v?.text||v?.summary||v?.title||"");}
function directionClass(v=""){const t=String(v).toLowerCase();if(/[上昇|強気|買い|反発|上向|up|bull]/.test(t))return"up";if(/[下落|弱気|売り|反落|下向|down|bear]/.test(t))return"down";return"neutral";}
function normalizeMarketName(raw){const d=decodeURIComponent(raw||"").trim();const f=Object.entries(MARKET_ALIASES).find(([,a])=>a.some(x=>x.toLowerCase()===d.toLowerCase()));return f?f[0]:d||"USD/JPY";}
function matchesMarket(m,n){const a=MARKET_ALIASES[n]||[n],h=[m?.name,m?.symbol,m?.ticker].filter(Boolean).join(" ").toLowerCase();return a.some(x=>h.includes(x.toLowerCase()));}
function findMarket(r,n){return asArray(r.markets).find(m=>matchesMarket(m,n));}
function reportText(r,m){return [r.title,r.theme,r.leadingMarket,...asArray(r.tags),...asArray(r.news),...asArray(r.crossAssetFlow),...asArray(r.positioning),...asArray(r.changes),...asArray(r.consistency),...asArray(r.events),m?.direction,m?.material,m?.positioning,m?.levels,m?.mainScenario,m?.alternativeScenario,m?.breakCondition,m?.risk].map(textOf).join(" ").toLowerCase();}
function extractThemes(r,m){const text=reportText(r,m),set=new Set();THEMES.forEach(([label,keys])=>{if(keys.some(k=>text.includes(k.toLowerCase())))set.add(label);});return set;}
function themeCounts(rows){const c=new Map();rows.forEach(({report,market})=>extractThemes(report,market).forEach(t=>c.set(t,(c.get(t)||0)+1)));return [...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"ja"));}
function jaccard(a,b){const u=new Set([...a,...b]);if(!u.size)return 0;let i=0;a.forEach(x=>{if(b.has(x))i++;});return i/u.size;}
function similarity(a,b){const theme=jaccard(extractThemes(a.report,a.market),extractThemes(b.report,b.market));const direction=directionClass(a.market.direction)===directionClass(b.market.direction)?1:0;const leader=a.report.leadingMarket&&b.report.leadingMarket&&String(a.report.leadingMarket).includes(String(b.report.leadingMarket))?1:0;const wordsA=new Set(tokenize(reportText(a.report,a.market))),wordsB=new Set(tokenize(reportText(b.report,b.market)));return Math.round((theme*.45+jaccard(wordsA,wordsB)*.35+direction*.15+leader*.05)*100);}
function tokenize(text){return String(text).toLowerCase().replace(/[、。・,./()（）「」『』:：;；!?！？]/g," ").split(/\s+/).flatMap(x=>x.match(/[a-z0-9/_-]+|[一-龠ぁ-んァ-ヶー]{2,}/gi)||[]).filter(x=>x.length>1&&!STOP_WORDS.has(x));}
function rowKey(row){return `${row.report.date}-${row.report.time||""}`;}
function scrollToRow(key){document.getElementById(`report-${key}`)?.scrollIntoView({behavior:"smooth",block:"start"});}

function renderStats(rows,name){const latest=rows[0],ranking=themeCounts(rows);marketPageTitle.textContent=`${name}｜市場別分析`;marketPageLead.textContent=`${name}に関する過去レポートを横断し、方向感、材料、需給、シナリオの変化を確認します。`;document.title=`${name}｜市場別分析｜マーケットレポート`;marketReportCount.textContent=`${rows.length}件`;marketLatestDirection.innerHTML=latest?`<span class="direction ${directionClass(latest.market.direction)}">${esc(latest.market.direction||"中立")}</span>`:"—";marketTopTheme.textContent=ranking[0]?.[0]||"集計対象なし";marketLatestDate.textContent=latest?`${latest.report.date.replaceAll("-","/")} ${latest.report.time||""}`:"—";document.querySelectorAll(".market-switcher a").forEach(a=>a.classList.toggle("active",normalizeMarketName(new URL(a.href).searchParams.get("market"))===name));}
function renderKpis(rows){const classes=rows.map(x=>directionClass(x.market.direction)),valid=classes.filter(x=>x!=="neutral"),up=valid.filter(x=>x==="up").length,down=valid.filter(x=>x==="down").length;bullishRate.textContent=valid.length?`${Math.round(up/valid.length*100)}%`:"—";bearishRate.textContent=valid.length?`${Math.round(down/valid.length*100)}%`:"—";let changes=0;for(let i=1;i<classes.length;i++){if(classes[i]!=="neutral"&&classes[i-1]!=="neutral"&&classes[i]!==classes[i-1])changes++;}directionChanges.textContent=`${changes}回`;const times=new Map();rows.forEach(x=>times.set(x.report.time||"時刻なし",(times.get(x.report.time||"時刻なし")||0)+1));dominantTime.textContent=[...times.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"—";}
function renderDirectionHistory(rows){const recent=rows.slice(0,12).reverse();directionHistory.innerHTML=recent.length?recent.map(({report,market})=>`<div class="history-item"><span class="history-date">${esc((report.date||"").slice(5).replace("-","/"))}<small>${esc(report.time||"")}</small></span><span class="history-line"></span><span class="direction ${directionClass(market.direction)}">${esc(market.direction||"中立")}</span></div>`).join(""):"<p class='empty compact-empty'>履歴がありません。</p>";}
function renderThemeRanking(rows){const ranking=themeCounts(rows).slice(0,8),max=ranking[0]?.[1]||1;marketThemeRanking.innerHTML=ranking.length?ranking.map(([label,count],i)=>`<div class="ranking-row"><span class="ranking-number">${i+1}</span><div class="ranking-main"><div class="ranking-label"><strong>${esc(label)}</strong><span>${count}回</span></div><div class="ranking-bar"><span style="width:${Math.max(8,count/max*100)}%"></span></div></div></div>`).join(""):"<p class='empty compact-empty'>集計できる材料がありません。</p>";}
function renderScenarioReview(rows){const pairs=[];for(let i=rows.length-1;i>0;i--){const current=rows[i],next=rows[i-1],forecast=directionClass(current.market.direction),actual=directionClass(next.market.direction);if(forecast!=="neutral"&&actual!=="neutral")pairs.push({...current,next,hit:forecast===actual});}const hits=pairs.filter(x=>x.hit).length,rate=pairs.length?Math.round(hits/pairs.length*100):null;scenarioReviewStatus.textContent=pairs.length?`${pairs.length}件を暫定評価`:"評価対象なし";scenarioReview.innerHTML=pairs.length?`<div class="scenario-score"><strong>${rate}%</strong><span>方向一致率</span><small>次回レポートの方向感を実績代理値として比較</small></div><div class="scenario-breakdown"><span class="scenario-hit">一致 ${hits}</span><span class="scenario-miss">不一致 ${pairs.length-hits}</span></div><div class="scenario-list">${pairs.slice(-6).reverse().map(x=>`<div class="scenario-row"><span>${esc(x.report.date.slice(5).replace("-","/"))}</span><span class="direction ${directionClass(x.market.direction)}">${esc(x.market.direction)}</span><span>→</span><span class="direction ${directionClass(x.next.market.direction)}">${esc(x.next.market.direction)}</span><strong class="${x.hit?"hit":"miss"}">${x.hit?"一致":"不一致"}</strong></div>`).join("")}</div><p class="analysis-caution">価格実績ではなく、次回レポートに記録された方向感との比較です。厳密な的中率には終値データの保存が必要です。</p>`:"<p class='empty compact-empty'>方向感を比較できるレポートが不足しています。</p>";}
function renderSimilar(rows){if(rows.length<2){marketSimilarReports.innerHTML="<p class='empty compact-empty'>比較対象がありません。</p>";return;}const latest=rows[0],results=rows.slice(1).map(row=>({row,score:similarity(latest,row)})).sort((a,b)=>b.score-a.score).slice(0,5);marketSimilarReports.innerHTML=results.map(({row,score},i)=>`<button class="similar-row" type="button" data-key="${esc(rowKey(row))}"><span class="similar-rank">${i+1}</span><span class="similar-content"><strong>${esc(row.report.date.replaceAll("-","/"))} ${esc(row.report.time||"")}</strong><small>${esc(row.report.theme||row.market.material||"テーマ記載なし")}</small></span><span class="similar-score">${score}%</span></button>`).join("");marketSimilarReports.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>scrollToRow(btn.dataset.key)));}
function renderTimeline(rows){const byMonth=new Map();[...rows].reverse().forEach(row=>{const month=row.report.date.slice(0,7);if(!byMonth.has(month))byMonth.set(month,[]);byMonth.get(month).push(row);});themeTimeline.innerHTML=[...byMonth.entries()].slice(-8).map(([month,items],i,all)=>{const top=themeCounts(items)[0]?.[0]||"テーマ不明";return `<div class="timeline-item"><div class="timeline-dot"></div><div><small>${esc(month.replace("-","/"))}</small><strong>${esc(top)}</strong><span>${items.length}件</span></div>${i<all.length-1?'<span class="timeline-arrow">↓</span>':""}</div>`;}).join("")||"<p class='empty compact-empty'>時系列を作成できません。</p>";}
function networkNodes(latest,name){const text=reportText(latest.report,latest.market);const candidates=[...THEMES.filter(([,keys])=>keys.some(k=>text.includes(k.toLowerCase()))).map(([label])=>label),latest.report.leadingMarket,name,...asArray(latest.report.crossAssetFlow).map(textOf)].filter(Boolean);return [...new Set(candidates.map(x=>String(x).trim()))].slice(0,6);}
function renderNetwork(rows,name){const latest=rows[0];if(!latest){marketNetwork.innerHTML=marketFlowMap.innerHTML="<p class='empty compact-empty'>フロー情報がありません。</p>";return;}const nodes=networkNodes(latest,name);marketNetwork.innerHTML=nodes.map((node,i)=>`<div class="network-node ${i===nodes.length-1?"target":""}" style="--i:${i};--n:${nodes.length}"><span>${esc(node)}</span></div>`).join("")+nodes.slice(1).map((_,i)=>`<span class="network-link link-${i}">→</span>`).join("");const flows=asArray(latest.report.crossAssetFlow).map(textOf).filter(Boolean),fallback=[latest.report.leadingMarket,latest.market.material,latest.market.mainScenario].filter(Boolean);const list=(flows.length?flows:fallback).slice(0,5);marketFlowMap.innerHTML=list.length?list.map((node,i)=>`<div class="flow-node"><span>${i+1}</span><p>${esc(node)}</p></div>${i<list.length-1?'<div class="flow-arrow">↓</div>':""}`).join(""):"<p class='empty compact-empty'>最新レポートにフロー記載がありません。</p>";}
function parseQuery(query){const lower=query.toLowerCase(),direction=/下落|弱気|売り|反落/.test(lower)?"down":/上昇|強気|買い|反発/.test(lower)?"up":null;const negatives=[...lower.matchAll(/(?:除く|以外|なし|ではない)\s*([^\s、。]+)/g)].map(x=>x[1]);const terms=tokenize(lower).filter(x=>!["上昇","下落","強気","弱気","買い","売り","反発","反落"].includes(x)&&!negatives.includes(x));return{direction,negatives,terms};}
function searchScore(row,parsed){const text=reportText(row.report,row.market),themes=extractThemes(row.report,row.market);if(parsed.direction&&directionClass(row.market.direction)!==parsed.direction)return 0;if(parsed.negatives.some(n=>text.includes(n)))return 0;let score=0;parsed.terms.forEach(term=>{if(text.includes(term))score+=term.length>4?3:2;THEMES.forEach(([label,keys])=>{if((label.includes(term)||keys.some(k=>k.toLowerCase().includes(term)))&&themes.has(label))score+=2;});});if(parsed.terms.length&&!parsed.terms.some(t=>text.includes(t)||[...themes].some(x=>x.includes(t))))return 0;return score+(parsed.direction?2:0);}
function runSearch(query){const parsed=parseQuery(query),results=currentRows.map(row=>({row,score:searchScore(row,parsed)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||rowKey(b.row).localeCompare(rowKey(a.row))).slice(0,12);marketSearchStatus.textContent=results.length?`「${query}」に近いレポート ${results.length}件`:"該当するレポートがありません。語を短くして再検索してください。";marketSearchResults.innerHTML=results.map(({row,score})=>`<button type="button" class="search-result-card" data-key="${esc(rowKey(row))}"><span><strong>${esc(row.report.date.replaceAll("-","/"))} ${esc(row.report.time||"")}</strong><small>${esc(row.market.direction||"中立")}｜関連度 ${score}</small></span><p>${esc(row.report.theme||row.market.material||"記載なし")}</p></button>`).join("");marketSearchResults.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>scrollToRow(btn.dataset.key)));}
function setupSearch(){marketSearchForm.addEventListener("submit",e=>{e.preventDefault();const q=marketSearchInput.value.trim();if(q)runSearch(q);});document.querySelectorAll(".search-suggestions button").forEach(btn=>btn.addEventListener("click",()=>{marketSearchInput.value=btn.textContent.trim();runSearch(marketSearchInput.value);}));}
function renderArchive(rows,name){marketArchiveCount.textContent=`${rows.length}件`;marketEmpty.hidden=rows.length!==0;marketArchive.innerHTML=rows.map(({report,market})=>`<article class="market-archive-card" id="report-${esc(rowKey({report,market}))}"><header><div><p class="archive-date">${esc(report.date.replaceAll("-","/"))} ${esc(report.time||"")}</p><h3>${esc(report.title||`${name}見通し`)}</h3></div><span class="direction ${directionClass(market.direction)}">${esc(market.direction||"中立")}</span></header>${market.price?`<p class="archive-price"><strong>${esc(market.price)}</strong>${market.change?` <span>${esc(market.change)}</span>`:""}</p>`:""}<div class="archive-grid"><section><h4>材料</h4><p>${esc(market.material||market.outlook||"記載なし")}</p></section><section><h4>需給・ポジション</h4><p>${esc(market.positioning||"記載なし")}</p></section><section><h4>メインシナリオ</h4><p>${esc(market.mainScenario||"記載なし")}</p></section><section><h4>崩れる条件</h4><p>${esc(market.breakCondition||"記載なし")}</p></section></div>${market.alternativeScenario?`<p class="archive-alt"><strong>代替シナリオ：</strong>${esc(market.alternativeScenario)}</p>`:""}${market.risk?`<p class="archive-risk"><strong>リスク：</strong>${esc(market.risk)}</p>`:""}<p class="archive-theme"><strong>全体テーマ：</strong>${esc(report.theme||"記載なし")}</p></article>`).join("");}

async function init(){const params=new URLSearchParams(location.search),name=normalizeMarketName(params.get("name")||params.get("market"));currentMarket=name;setupSearch();try{const response=await fetch(`reports.json?ts=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error("reports.jsonを取得できませんでした。");const data=await response.json();if(!Array.isArray(data))throw new Error("レポート一覧の形式が正しくありません。");currentRows=data.filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date||"")).map(report=>({report,market:findMarket(report,name)})).filter(x=>x.market).sort((a,b)=>(`${b.report.date} ${b.report.time}`).localeCompare(`${a.report.date} ${a.report.time}`));renderStats(currentRows,name);renderKpis(currentRows);renderDirectionHistory(currentRows);renderThemeRanking(currentRows);renderScenarioReview(currentRows);renderSimilar(currentRows);renderTimeline(currentRows);renderNetwork(currentRows,name);renderArchive(currentRows,name);}catch(error){marketPageTitle.textContent="市場別分析を表示できません";marketPageLead.textContent=error.message;marketArchive.innerHTML=`<p class="empty">${esc(error.message)}</p>`;marketEmpty.hidden=true;}}
init();
