const RR_ALIASES={"USD/JPY":["USD/JPY","USDJPY","ドル円"],"EUR/USD":["EUR/USD","EURUSD","ユーロドル"],"日経225先物":["日経225先物","日経先物","大阪取引所"],"金":["金","ゴールド","Gold","XAUUSD"],"原油":["原油","WTI","ブレント","Crude Oil"],"BTCUSD":["BTCUSD","BTC/USD","ビットコイン","Bitcoin"]};
function rrArray(v){return Array.isArray(v)?v:(v?[v]:[]);}
function rrName(raw=""){const decoded=decodeURIComponent(raw).trim();const found=Object.entries(RR_ALIASES).find(([,aliases])=>aliases.some(alias=>alias.toLowerCase()===decoded.toLowerCase()));return found?.[0]||decoded||"USD/JPY";}
function rrMatch(market,name){const text=[market?.name,market?.symbol,market?.ticker].filter(Boolean).join(" ").toLowerCase();return (RR_ALIASES[name]||[name]).some(alias=>text.includes(alias.toLowerCase()));}
function rrText(report,market){return [report?.title,report?.theme,report?.leadingMarket,...rrArray(report?.news),...rrArray(report?.crossAssetFlow),...rrArray(report?.positioning),...rrArray(report?.events),...rrArray(report?.changes),market?.direction,market?.price,market?.material,market?.outlook,market?.positioning,market?.levels,market?.mainScenario,market?.alternativeScenario,market?.breakCondition,market?.risk].filter(Boolean).join(" ");}
function rrChecks(report,market){const text=rrText(report,market);const checks=[
  ["価格・方向感",Boolean(market?.price)&&Boolean(market?.direction),"最新価格または基準価格と方向感を明記"],
  ["主要材料",Boolean(market?.material||report?.theme||rrArray(report?.news).length),"値動きの主因となる材料を明記"],
  ["金利・為替連動",/金利|利回り|ドル|円|為替|FRB|FOMC|日銀|ECB/i.test(text),"金利・為替との伝播経路を確認"],
  ["クロスアセットフロー",rrArray(report?.crossAssetFlow).length>0||/資金フロー|流入|流出|買われ|売られ/i.test(text),"何が買われ、何が売られたかを整理"],
  ["需給・ポジション",Boolean(market?.positioning||rrArray(report?.positioning).length)||/需給|ポジション|建玉|CTA|ガンマ|ETF|出来高/i.test(text),"先物・オプション・実需・ファンドフローを確認"],
  ["メインシナリオ",Boolean(market?.mainScenario||market?.outlook),"中心シナリオと想定方向を明記"],
  ["代替シナリオ",Boolean(market?.alternativeScenario),"想定外の展開に備えた代替シナリオを明記"],
  ["崩れる条件",Boolean(market?.breakCondition||market?.risk),"シナリオ無効化条件とリスクを明記"],
  ["今後のイベント",rrArray(report?.events).length>0||/CPI|雇用統計|FOMC|日銀|決算|入札|SQ|MSQ|会見/i.test(text),"次に相場を動かすイベントを明記"],
  ["検証用 outcomes",Boolean(market?.outcomes&&Object.keys(market.outcomes).length),"将来の実価格検証に使う outcomes を記録"]
];return checks.map(([label,pass,advice])=>({label,pass,advice}));}
function rrScore(checks){return Math.round(checks.filter(x=>x.pass).length/checks.length*100);}
function buildReportReview(rows){if(document.querySelector(".report-review-panel"))return;const panel=document.createElement("section");panel.className="report-review-panel";const row=rows[0];if(!row){panel.innerHTML='<p class="rr-empty">レビュー対象のレポートがありません。</p>';document.querySelector(".natural-search-section")?.before(panel);return;}const checks=rrChecks(row.report,row.market),score=rrScore(checks),missing=checks.filter(x=>!x.pass);const grade=score>=90?"A":score>=75?"B":score>=60?"C":"D";panel.innerHTML=`<div class="rr-head"><div><span>REPORT REVIEW</span><h2>最新レポート自動レビュー</h2></div><div class="rr-score"><strong>${score}</strong><span>/100</span><b>評価 ${grade}</b></div></div><div class="rr-meter"><span style="width:${score}%"></span></div><div class="rr-grid">${checks.map(item=>`<article class="${item.pass?"pass":"miss"}"><span>${item.pass?"✓":"!"}</span><div><strong>${item.label}</strong><small>${item.pass?"記載あり":item.advice}</small></div></article>`).join("")}</div><div class="rr-priority"><h3>次回レポートで優先して補う項目</h3>${missing.length?`<ol>${missing.slice(0,5).map(item=>`<li><strong>${item.label}</strong><span>${item.advice}</span></li>`).join("")}</ol>`:'<p>主要項目はそろっています。次は記載内容の精度と実価格検証を確認してください。</p>'}</div><p class="rr-note">このレビューは reports.json に保存された項目の有無を点検します。事実の正確性そのものは、別途データソースとの照合が必要です。</p>`;document.querySelector(".natural-search-section")?.before(panel);}
async function initReportReview(){try{const params=new URLSearchParams(location.search),name=rrName(params.get("market")||params.get("name")||"");const response=await fetch(`reports.json?review=${Date.now()}`,{cache:"no-store"});if(!response.ok)return;const reports=await response.json();if(!Array.isArray(reports))return;const rows=reports.flatMap(report=>rrArray(report.markets).filter(market=>rrMatch(market,name)).map(market=>({report,market}))).sort((a,b)=>`${b.report?.date||""} ${b.report?.time||""}`.localeCompare(`${a.report?.date||""} ${a.report?.time||""}`));buildReportReview(rows);}catch(error){console.warn("Report review could not be built",error);}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initReportReview);else initReportReview();
