const latestReport=document.getElementById("latestReport");
const latestTimestamp=document.getElementById("latestTimestamp");
const reportList=document.getElementById("reportList");
const timeFilter=document.getElementById("timeFilter");
const monthFilter=document.getElementById("monthFilter");
const marketFilter=document.getElementById("marketFilter");
const searchInput=document.getElementById("searchInput");
const resultCount=document.getElementById("resultCount");
const emptyMessage=document.getElementById("emptyMessage");
const loadMoreButton=document.getElementById("loadMoreButton");
const latestSection=document.getElementById("latestSection");
const heroStatus=document.getElementById("heroStatus");
const dashboardTimestamp=document.getElementById("dashboardTimestamp");
const dashboardTheme=document.getElementById("dashboardTheme");
const dashboardLeader=document.getElementById("dashboardLeader");
const dashboardConsistency=document.getElementById("dashboardConsistency");
const dashboardPositioning=document.getElementById("dashboardPositioning");
const dashboardNews=document.getElementById("dashboardNews");
const dashboardFlow=document.getElementById("dashboardFlow");
const dashboardHandover=document.getElementById("dashboardHandover");
const dashboardMarkets=document.getElementById("dashboardMarkets");
const analysisStatus=document.getElementById("analysisStatus");
const themeRanking=document.getElementById("themeRanking");
const similarReports=document.getElementById("similarReports");
let reports=[];
let visibleCount=20;

const THEME_DICTIONARY=[
  ["米金利",["米金利","米長期金利","米10年債","米国債利回り","長期金利"]],
  ["円安・円高",["円安","円高","ドル円","USD/JPY","円買い","円売り"]],
  ["AI・半導体",["AI","人工知能","半導体","NASDAQ","エヌビディア","NVIDIA"]],
  ["原油・エネルギー",["原油","WTI","ブレント","OPEC","エネルギー","ガソリン"]],
  ["金・安全資産",["金","ゴールド","安全資産","地金"]],
  ["地政学",["地政学","戦争","紛争","制裁","中東","ホルムズ","ロシア","ウクライナ"]],
  ["金融政策",["利上げ","利下げ","金融政策","FRB","FOMC","日銀","ECB"]],
  ["インフレ",["インフレ","CPI","PCE","物価","関税"]],
  ["景気・雇用",["景気","雇用","失業率","PMI","GDP","消費"]],
  ["暗号資産",["BTC","ビットコイン","暗号資産","仮想通貨","ETF資金"]],
  ["日経先物需給",["日経225先物","日経先物","SQ","MSQ","オプション","先物需給"]],
  ["リスクオン・オフ",["リスクオン","リスクオフ","安全逃避","リスク選好"]]
];

function esc(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function asArray(value){return Array.isArray(value)?value:(value?[value]:[]);}
function itemText(item){return typeof item==="string"?item:(item?.text||item?.summary||item?.title||JSON.stringify(item));}
function listText(items=[]){const rows=asArray(items);return rows.length?rows.map(x=>`<p>・${esc(itemText(x))}</p>`).join(""):"<p>記載なし</p>";}
function compactList(items=[],limit=3){const rows=asArray(items).slice(0,limit);return rows.length?rows.map(x=>`<p>・${esc(itemText(x))}</p>`).join(""):"<p>記載なし</p>";}
function directionClass(value=""){const text=String(value).toLowerCase();if(/[上昇|強気|買い|反発|up|bull]/.test(text))return "up";if(/[下落|弱気|売り|反落|down|bear]/.test(text))return "down";return "neutral";}
function formatMonth(value=""){const [y,m]=value.split("-");return `${y}年${Number(m)}月`;}
function optionalPanel(title,content){return content?`<section class="panel"><h4>${esc(title)}</h4>${content}</section>`:"";}
function sourceList(items=[]){const rows=asArray(items);if(!rows.length)return "";return `<section class="sources"><h4>主な情報源</h4><ul>${rows.map(source=>{if(typeof source==="string")return `<li>${esc(source)}</li>`;const name=esc(source.name||source.title||"情報源");const url=source.url?`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${name}</a>`:name;return `<li>${url}${source.note?` — ${esc(source.note)}`:""}</li>`;}).join("")}</ul></section>`;}
function reportText(report){return [report.theme,report.leadingMarket,...asArray(report.tags),...asArray(report.changes),...asArray(report.consistency),...asArray(report.positioning),...asArray(report.news),...asArray(report.crossAssetFlow),...asArray(report.sectors),...asArray(report.events),...asArray(report.handover),...asArray(report.markets).flatMap(m=>[m.name,m.direction,m.material,m.positioning,m.mainScenario,m.alternativeScenario])].map(itemText).join(" ").toLowerCase();}
function extractThemes(report){const text=reportText(report);const themes=new Set();THEME_DICTIONARY.forEach(([label,keywords])=>{if(keywords.some(keyword=>text.includes(keyword.toLowerCase())))themes.add(label);});asArray(report.tags).forEach(tag=>themes.add(String(tag)));return themes;}
function marketDirectionMap(report){return new Map(asArray(report.markets).map(m=>[m.name,directionClass(m.direction)]));}
function setSimilarity(a,b){const union=new Set([...a,...b]);if(!union.size)return 0;let intersection=0;a.forEach(x=>{if(b.has(x))intersection+=1;});return intersection/union.size;}
function reportSimilarity(current,candidate){const themeScore=setSimilarity(extractThemes(current),extractThemes(candidate));const tagScore=setSimilarity(new Set(asArray(current.tags)),new Set(asArray(candidate.tags)));const aMarkets=marketDirectionMap(current),bMarkets=marketDirectionMap(candidate);let comparable=0,matches=0;aMarkets.forEach((direction,name)=>{if(bMarkets.has(name)){comparable+=1;if(direction===bMarkets.get(name))matches+=1;}});const marketScore=comparable?matches/comparable:0;const leaderScore=current.leadingMarket&&candidate.leadingMarket&&String(current.leadingMarket).includes(String(candidate.leadingMarket))?1:0;return Math.round((themeScore*.45+tagScore*.15+marketScore*.3+leaderScore*.1)*100);}

function renderThemeRanking(){const counts=new Map();reports.forEach(report=>extractThemes(report).forEach(theme=>counts.set(theme,(counts.get(theme)||0)+1)));const ranking=[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"ja")).slice(0,10);const max=ranking[0]?.[1]||1;themeRanking.innerHTML=ranking.length?ranking.map(([theme,count],index)=>`<div class="ranking-row"><span class="ranking-number">${index+1}</span><div class="ranking-main"><div class="ranking-label"><strong>${esc(theme)}</strong><span>${count}回</span></div><div class="ranking-bar"><span style="width:${Math.max(8,count/max*100)}%"></span></div></div></div>`).join(""):"<p class='empty compact-empty'>集計できるテーマがありません。</p>";}
function renderSimilarReports(){if(reports.length<2){similarReports.innerHTML="<p class='empty compact-empty'>比較対象のレポートがまだありません。</p>";return;}const current=reports[0];const results=reports.slice(1).map(report=>({report,score:reportSimilarity(current,report)})).sort((a,b)=>b.score-a.score).slice(0,5);similarReports.innerHTML=results.map(({report,score},index)=>`<button class="similar-row" type="button" data-date="${esc(report.date)}" data-time="${esc(report.time)}"><span class="similar-rank">${index+1}</span><span class="similar-content"><strong>${esc((report.date||"").replaceAll("-","/"))} ${esc(report.time||"")}</strong><small>${esc(report.theme||report.leadingMarket||"テーマ記載なし")}</small></span><span class="similar-score">${score}%</span></button>`).join("");similarReports.querySelectorAll(".similar-row").forEach(button=>button.addEventListener("click",()=>openReport(button.dataset.date,button.dataset.time)));}
function renderAnalysis(){renderThemeRanking();renderSimilarReports();analysisStatus.textContent=`${reports.length}件のレポートを分析`;}

function marketCards(item,marketName="all"){return asArray(item.markets).filter(m=>marketName==="all"||m.name===marketName).map(m=>`<div class="market-item"><div class="market-title-row"><h5>${esc(m.name)}</h5><span class="direction ${directionClass(m.direction)}">${esc(m.direction||"方向感なし")}</span></div>${m.price?`<p class="price-line"><strong>${esc(m.price)}</strong>${m.change?` <span>${esc(m.change)}</span>`:""}</p>`:""}<p><strong>材料：</strong>${esc(m.material||m.outlook||"記載なし")}</p>${m.positioning?`<p><strong>需給：</strong>${esc(m.positioning)}</p>`:""}${m.levels?`<p><strong>注目水準：</strong>${esc(m.levels)}</p>`:""}${m.mainScenario?`<p><strong>メイン：</strong>${esc(m.mainScenario)}</p>`:""}${m.alternativeScenario?`<p><strong>代替：</strong>${esc(m.alternativeScenario)}</p>`:""}<p><strong>崩れる条件：</strong>${esc(m.breakCondition||"記載なし")}</p>${m.risk?`<p><strong>リスク：</strong>${esc(m.risk)}</p>`:""}</div>`).join("");}
function reportCard(item,marketName="all"){const markets=marketCards(item,marketName);const scenarios=optionalPanel("全体シナリオ",`${item.mainScenario?`<p><strong>メイン：</strong>${esc(item.mainScenario)}</p>`:""}${item.alternativeScenario?`<p><strong>代替：</strong>${esc(item.alternativeScenario)}</p>`:""}${item.breakConditions?`<p><strong>崩れる条件：</strong>${esc(item.breakConditions)}</p>`:""}`);const events=optionalPanel("今後のイベント",listText(item.events));const sectors=optionalPanel("セクター・業種動向",listText(item.sectors));const flows=optionalPanel("クロスアセット資金フロー",listText(item.crossAssetFlow));const risk=optionalPanel("リスク管理",listText(item.riskManagement));return `<article class="report-card"><header class="report-head"><h3>${esc(item.title)}</h3><p class="meta">${esc((item.date||"").replaceAll("-","/"))} ${esc(item.time)}｜${esc(asArray(item.tags).join("・"))}</p></header><div class="report-body"><div class="theme"><strong>今日の相場テーマ</strong>${esc(item.theme||"記載なし")}</div><div class="section-grid"><section class="panel"><h4>前回からの変化</h4>${listText(item.changes)}</section><section class="panel"><h4>材料と値動きの整合性</h4>${listText(item.consistency)}</section><section class="panel"><h4>今日の主導市場</h4><p>${esc(item.leadingMarket||"記載なし")}</p></section><section class="panel"><h4>ポジションの偏り</h4>${listText(item.positioning)}</section><section class="panel"><h4>重要ニュース</h4>${listText(item.news)}</section><section class="panel"><h4>次の時間帯への引き継ぎ</h4>${listText(item.handover)}</section>${flows}${sectors}${events}${scenarios}${risk}</div><h4 class="market-heading">個別市場見通し</h4><div class="market-grid">${markets||"<p>該当市場の記載がありません。</p>"}</div>${sourceList(item.sources)}</div></article>`;}
function renderDashboard(item){if(!item)return;const stamp=`${(item.date||"").replaceAll("-","/")} ${item.time||""}`.trim();dashboardTimestamp.textContent=`最終更新 ${stamp}`;heroStatus.textContent=`最新レポート ${stamp}`;dashboardTheme.textContent=item.theme||"記載なし";dashboardLeader.textContent=item.leadingMarket||"記載なし";dashboardConsistency.innerHTML=compactList(item.consistency,3);dashboardPositioning.innerHTML=compactList(item.positioning,3);dashboardNews.innerHTML=compactList(item.news,4);dashboardFlow.innerHTML=compactList(item.crossAssetFlow,4);dashboardHandover.innerHTML=compactList(item.handover,4);dashboardMarkets.innerHTML=asArray(item.markets).slice(0,6).map(m=>`<article class="ticker-card"><div class="ticker-top"><h3>${esc(m.name||"市場")}</h3><span class="direction ${directionClass(m.direction)}">${esc(m.direction||"中立")}</span></div>${m.price?`<p class="ticker-price">${esc(m.price)}</p>`:"<p class='ticker-price'>—</p>"}<p class="ticker-change">${esc(m.change||"変化記載なし")}</p><p class="ticker-material">${esc(m.material||m.outlook||"材料記載なし")}</p></article>`).join("")||"<p class='empty'>市場データがありません。</p>";}

function timeClass(time=""){return `time-${String(time).replace(":","")}`;}
function archiveSummary(item){const candidates=[item.theme,item.leadingMarket,...asArray(item.news).map(itemText),...asArray(item.changes).map(itemText),...asArray(item.crossAssetFlow).map(itemText)].filter(Boolean);const text=candidates.join("　").replace(/\s+/g," ").trim();return text.length>190?`${text.slice(0,190)}…`:text||"要約はありません。";}
function archiveTags(item){const tags=[...new Set([...asArray(item.tags),...extractThemes(item)])].filter(Boolean).slice(0,6);return tags.map(tag=>`<span class="archive-tag">${esc(tag)}</span>`).join("");}
function archiveCard(item){return `<button class="archive-card ${timeClass(item.time)}" type="button" data-date="${esc(item.date)}" data-time="${esc(item.time)}"><div class="archive-card-top"><span class="time-badge">${esc(item.time||"時刻不明")}</span><span class="archive-date">${esc((item.date||"").replaceAll("-","/"))}</span></div><h3>${esc(item.title||`マーケットレポート｜${item.date} ${item.time}`)}</h3><p>${esc(archiveSummary(item))}</p><div class="archive-tags">${archiveTags(item)}</div><span class="archive-open">全文を表示 →</span></button>`;}
function openReport(date,time){const target=reports.find(r=>r.date===date&&r.time===time);if(!target)return;latestReport.innerHTML=reportCard(target,marketFilter.value);latestTimestamp.textContent=`選択中 ${target.date.replaceAll("-","/")} ${target.time}`;latestSection.scrollIntoView({behavior:"smooth",block:"start"});}
function populateMonths(){const months=[...new Set(reports.map(r=>(r.date||"").slice(0,7)).filter(Boolean))].sort().reverse();monthFilter.innerHTML='<option value="all">すべて</option>'+months.map(m=>`<option value="${esc(m)}">${esc(formatMonth(m))}</option>`).join("");}
function filteredReports(){const time=timeFilter.value,month=monthFilter.value,market=marketFilter.value,query=searchInput.value.trim().toLowerCase();return reports.filter(report=>{const hasMarket=market==="all"||asArray(report.markets).some(m=>m.name===market)||asArray(report.tags).includes(market);const haystack=JSON.stringify(report).toLowerCase();return (time==="all"||report.time===time)&&(month==="all"||(report.date||"").startsWith(month))&&hasMarket&&(!query||haystack.includes(query));});}
function render(){const filtered=filteredReports();const shown=filtered.slice(0,visibleCount);reportList.innerHTML=shown.map(archiveCard).join("");reportList.querySelectorAll(".archive-card").forEach(button=>button.addEventListener("click",()=>openReport(button.dataset.date,button.dataset.time)));resultCount.textContent=`${filtered.length}件中 ${shown.length}件を表示`;emptyMessage.hidden=filtered.length!==0;loadMoreButton.hidden=shown.length>=filtered.length;}
function resetAndRender(){visibleCount=20;render();}
async function init(){try{const response=await fetch(`reports.json?ts=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error("reports.jsonを取得できませんでした。");const data=await response.json();if(!Array.isArray(data))throw new Error("レポート一覧の形式が正しくありません。");reports=data.filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date||"")).sort((a,b)=>(`${b.date} ${b.time}`).localeCompare(`${a.date} ${a.time}`));populateMonths();if(reports[0]){renderDashboard(reports[0]);renderAnalysis();latestReport.innerHTML=reportCard(reports[0]);latestTimestamp.textContent=`最終更新 ${reports[0].date.replaceAll("-","/")} ${reports[0].time}`;}else{latestReport.innerHTML="<p class='empty'>レポートがありません。</p>";heroStatus.textContent="レポートなし";analysisStatus.textContent="分析対象なし";}render();}catch(error){latestReport.innerHTML=`<p class="empty">${esc(error.message)}</p>`;reportList.innerHTML="";resultCount.textContent="0件";heroStatus.textContent="データ取得エラー";dashboardTheme.textContent="データを取得できませんでした";analysisStatus.textContent="分析エラー";}}
[timeFilter,monthFilter,marketFilter].forEach(element=>element.addEventListener("change",resetAndRender));searchInput.addEventListener("input",resetAndRender);loadMoreButton.addEventListener("click",()=>{visibleCount+=20;render();});init();